# 6. NumPy
NumPy 是一个强大的 Python 的数学计算库，可以处理例如矩阵乘法、统计函数等数学操作。

（若在自己的电脑上运行 NumPy，请先安装 NumPy：）

In [ ]:
%pip install numpy

要在 Python 里调用一个库，使用 `import <package> as <name>` 的语法就可以了。

In [1]:
import numpy as np

## 数组 `np.array`
为什么我们要用 NumPy 呢？这是因为它可以以数组的结构，存储并操作大量数据。一个基本的数组可以是一个 1 维的向量。下面就是几种创建向量数组的方式：

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
c = np.arange(4)  # 相当于 Python range(4)
d = np.zeros(4)  # 全是 0 的长度为 4 的向量
e = np.ones(4)  # 全是 1 的长度为 4 的向量

print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3 4]
[4 3 2 1]
[0 1 2 3]
[0. 0. 0. 0.]
[1. 1. 1. 1.]


用 NumPy 的好处就是可以对大批数据进行各种操作，比如加减乘除：

In [3]:
# 对每个元素操作
print(a + 1)
print(a - 1)
print(a * 1)
print(a / 1)

# 对 a 和 b 之间对应的元素操作
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[2 3 4 5]
[0 1 2 3]
[1 2 3 4]
[1. 2. 3. 4.]
[5 5 5 5]
[-3 -1  1  3]
[4 6 6 4]
[0.25       0.66666667 1.5        4.        ]


是不是很方便呢？注意，我们现在不需要 `for` 语法，就可以来对一组数据操作了。

我们在线性代数里学习了点乘，那如果我们要点乘 $a \cdot b = [1, 2, 3, 4] \cdot [4, 3, 2, 1]$，该怎么做呢？

In [4]:
np.dot(a, b)

20

## 2 维矩阵和数组形状
我们看到了怎么在数组里创建 1 维的向量，那怎么创建 2 维的矩阵呢？使用多层的列表 `list` 就可以了：

In [5]:
f = np.array([[1, 2, 3], [4, 5, 6]])
print(f)

[[1 2 3]
 [4 5 6]]


上面的 `f` 就是一个 2 × 3 的矩阵。要查看它的形状等信息，可以用 `f.ndim`、`f.shape` 和 `f.size`：

In [6]:
print(f.ndim)   # 2 维矩阵
print(f.shape)  # (2 × 3) 的形状
print(f.size)   # 6 个总共元素

2
(2, 3)
6


那我们要改变 `f` 的形状，怎么办呢？

In [7]:
print(f)

[[1 2 3]
 [4 5 6]]


要做矩阵置换可以用 `.transpose()`：

In [8]:
print(f.transpose())

[[1 4]
 [2 5]
 [3 6]]


矩阵展开成一个 1 维向量 `.flatten()`：

In [9]:
print(f.flatten())

[1 2 3 4 5 6]


转换成给定的形状（3 × 2）`.reshape(shape)`：

In [10]:
print(f.reshape((3, 2)))

[[1 2]
 [3 4]
 [5 6]]


同样地，我们可以对矩阵进行各种计算。比如说，如果我们要算 `f` 和它的置换的乘积 $\mathbf{F}\mathbf{F}^\top$ 的话，可以用 `np.matmul`：

In [11]:
ft = f.transpose()
np.matmul(f, ft)

array([[14, 32],
       [32, 77]])

或者用 `@` 来更简便地写矩阵乘积：

In [12]:
f @ ft

array([[14, 32],
       [32, 77]])

## 数组索引
如果我们想要访问 1 维向量里面的个别元素，可以用和 `list` 一样的方法 `a[index]`（注意索引 `index` 从 0 开始算）：

In [13]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])  # 长度为 8 的数组

print(a)
print(a[1])    # 第 2 个元素
print(a[1:])   # 第 2（含）个之后的所有元素
print(a[:1])   # 第 2（不含）个之前的所有元素
print(a[1:3])  # 第 2（含）到 4（不含）个元素

[1 2 3 4 5 6 7 8]
2
[2 3 4 5 6 7 8]
[1]
[2 3]


但是如果是多维数组，比如 2 维的矩阵或者 3 维的张量，怎么访问它的元素呢？我们可以在 `[]` 里间加逗号 `,` 分隔每个轴的索引：

In [14]:
a = np.arange(9).reshape((3, 3))  # 3 × 3 矩阵

print(a)
print(a[1, 2])   # 第 2 行第 3 列
print(a[1, 1:])  # 第 2 行第 2+ 列（第 2（含）以上的列）
print(a[1, :1])  # 第 2 行第 2- 列（第 2（不含）以下的列）
print(a[1, :])   # 第 2 行所有列
print(a[1:, 0])  # 第 2+ 行第 1 列

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5
[4 5]
[3]
[3 4 5]
[3 6]


同样地，3 维张量也可以做类似的操作：

In [15]:
a = np.arange(27).reshape((3, 3, 3))  # 3 × 3 × 3 张量

print(a)
print(a[0, 1, 2])
print(a[0, :, 2])
# 以此类推

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
5
[2 5 8]


## 其它函数
NumPy 提供了很多方便的数学函数，请见下面代码例子：

In [16]:
a = np.array([1, 2, 3])
print(np.log(a))  # 自然对数
print(np.exp(a))  # e 的 a 次方
print(np.sin(a))  # 正弦 sin
print(np.cos(a))  # 余弦 cos

print(np.sum(a))  # a 向量之和（也可以写作 a.sum()，下同）
print(np.mean(a)) # a 的平均值
print(np.std(a))  # a 的标准差
print(np.max(a))  # a 的最大值
print(np.min(a))  # a 的最小值
print(np.argmax(a))  # a 的最大值位置
print(np.argmin(a))  # a 的最小值位置

[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
6
2.0
0.816496580927726
3
1
2
0


这些函数很好用，但是不需要一次全部记住，只要需要用的时候来看一眼它们的名字，或者网上查一下就可以了！

## 任务
你可以求出下面这个矩阵第 1 行、第 2 列的值的自然对数吗？

In [17]:
a = np.random.randn(3, 3)  # np.random.randn 是创建随机化的数组的意思
a

array([[ 0.08815935, -0.14142467,  1.52216895],
       [-0.31820414, -0.48454439,  0.93834037],
       [-0.26578955, -0.56698932,  0.20433691]])

## 小结
这一章我们学习了 NumPy 库里面的数组以及它们的各种运算方法。